# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Url', models.URLField(max_length=2048, verbose_name='url')),
                ('FoundDateTime', models.DateTimeField(verbose_name='date found')),
                ('LastScanDate', models.DateTimeField(verbose_name='last scan date')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPageRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField()),
                ('PageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Pages')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='personpagerank',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Persons'),
        ),
        migrations.AddField(
            model_name='pages',
            name='SiteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Sites'),
        ),
        migrations.AddField(
            model_name='keywords',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Persons'),
        ),
    ]
