# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Url', models.URLField(max_length=2048, verbose_name='url')),
                ('FoundDateTime', models.DateTimeField(verbose_name='date found')),
                ('LastScanDate', models.DateTimeField(blank=True, null=True, verbose_name='last scan date')),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='PersonPageRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField()),
                ('PageID', models.ForeignKey(db_column='PageID', on_delete=django.db.models.deletion.CASCADE, to='restapi.Pages')),
            ],
            options={
                'db_table': 'person_page_rank',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.AddField(
            model_name='personpagerank',
            name='PersonID',
            field=models.ForeignKey(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, to='restapi.Persons'),
        ),
        migrations.AddField(
            model_name='pages',
            name='SiteID',
            field=models.ForeignKey(db_column='SiteID', on_delete=django.db.models.deletion.CASCADE, to='restapi.Sites'),
        ),
        migrations.AddField(
            model_name='keywords',
            name='PersonID',
            field=models.ForeignKey(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, to='restapi.Persons'),
        ),
    ]
