# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='Hash_url',
            field=models.URLField(default=1, max_length=32, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personpagerank',
            name='Scan_date_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scan Date Datetime'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='Url',
            field=models.URLField(max_length=128, verbose_name='url'),
        ),
    ]
