# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20170728_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='User',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
    ]
