# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20170728_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='User',
            new_name='UserID',
        ),
    ]
