# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0007_auto_20170728_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='UserID',
            field=models.ForeignKey(blank=True, db_column='username', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pages',
            name='Hash_url',
            field=models.URLField(max_length=32, unique=True, verbose_name='hash_url'),
        ),
        migrations.AlterField(
            model_name='personpagerank',
            name='PageID',
            field=models.ForeignKey(db_column='PageID', on_delete=django.db.models.deletion.CASCADE, related_name='page_id', to='restapi.Pages'),
        ),
    ]
