# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20170813_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='Url',
            field=models.URLField(max_length=254, unique=True, verbose_name='url'),
        ),
    ]
