# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_auto_20170813_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='Hash_url',
            field=models.URLField(max_length=64, unique=True, verbose_name='hash_url'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='Url',
            field=models.URLField(max_length=128, verbose_name='url'),
        ),
    ]
